graph LR
    A["Logger.php\nLOC 32 | WMC 3 | CBO 1"] --> B["IntegrationController.php\nLOC 64 | WMC 3 | CBO 2"]
    B --> C["ServiceConnector.php\nLOC 78 | WMC 4 | CBO 3"]
    B --> D["ProductoDAO.php\nLOC 55 | WMC 4 | CBO 2"]
    D --> E["Producto.php\nLOC 26 | WMC 2 | CBO 0"]
